import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './Components/Header'
import HomeWrapper from './Components/Home'
export default function Home() {
  return (
    <>
      <Head>
        <title>  Sama Babaee </title>
        <meta name="description" content="Generated by sama babaee" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="img/favicon.ico" />
      </Head>
      <main className={`${styles.main}  container-xxl`} >

        <Header />
        <HomeWrapper />

      </main>
    </>
  )
}
